import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomLink from "./components/CustomLink";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* navbar */}
        <nav className="p-4 border-b border-gray-400">
          <ul className="flex gap-5">
            <li>
              <CustomLink path='/'>Home</CustomLink>
            </li>
            <li>
              <CustomLink path='/about'>about</CustomLink>
            </li>
            <li>
              <CustomLink prefetch={false} path='/dashboard/settings'>settings</CustomLink>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
